# Spring Boot Actuator (Monitoring & Health Checks)
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Enable all Actuator endpoints

logging:
  level:
    root: WARN  # Set logging level to WARN
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) %clr([%thread]){cyan} %clr(%logger{36}){magenta} - %msg%n"

# Config Server (Externalise Services Configuration)
server:
  port: 8888  # Default port for Config Server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Oluwafisayomi-P-Folaranmi/spring-config  # Your Git repo
          default-label: main  # Branch name
  application:
    name: config-server  # Name of the config server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Register Config Server in Eureka
